- create:
    - ~/.config/pgcli/
    - ~/.config/htop/
    - ~/.config/youtube-dl/

- link:
    ~/.digrc: terminals/misc/digrc
    ~/.gemrc: terminals/misc/gemrc
    ~/.mtrrc: terminals/misc/mtrrc
    ~/.wgetrc: terminals/misc/wgetrc
    ~/.curlrc: terminals/misc/curlrc
    ~/.psqlrc: terminals/misc/psqlrc
    ~/.Xresources: terminals/misc/Xresources
    ~/.ansiweatherrc: terminals/misc/ansiweatherrc
    ~/.config/pgcli/config: apps/pgcli/config
    ~/.config/htop/htoprc: apps/htop/htoprc
    ~/.config/youtube-dl/config: apps/youtube-dl/config
