- pip:
    file: tools/pip/requirements-user.txt
    binary: /usr/local/bin/pip3
    user: true
    stdout: false
    stderr: true

- pipx:
    file: tools/pip/requirements-pipx.txt
    stdout: false
    stderr: true
