- create:
    - ~/.config/byobu

- link:
    ~/.screenrc: terminals/screen/screenrc
    ~/.tmux.conf: terminals/tmux/tmux.conf
    ~/.tmuxcolors.conf: terminals/tmux/colors/tmuxcolors-dark.conf
    ~/.byobu: ~/.config/byobu
    ~/.config/byobu: terminals/byobu
# - shell:
#     - [tmux source-file ~/.tmux.conf || true, Sourcing new tmux configuration]
