- shell:
    - [
        git clone https://github.com/SpaceVim/SpaceVim.git ~/.SpaceVim,
        Installing SpaceVim,
      ]

- link:
    ~/.vim: ~/.SpaceVim
    ~/.config/nvim: ~/.SpaceVim
    ~/.SpaceVim.d: apps/vim/SpaceVim.d
